# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'gamenewab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from play import *
from instruc import *
class Ui_MainWindow(object):
    a=True
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(939, 762)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labep1 = QtWidgets.QLabel(self.centralwidget)
        self.labep1.setGeometry(QtCore.QRect(20, 20, 901, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.labep1.setFont(font)
        self.labep1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255));")
        self.labep1.setObjectName("labep1")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(140, 630, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reset.setFont(font)
        self.reset.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.reset.setObjectName("reset")
        self.instructions = QtWidgets.QPushButton(self.centralwidget)
        self.instructions.setGeometry(QtCore.QRect(420, 630, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.instructions.setFont(font)
        self.instructions.setStyleSheet("background-color: rgb(255, 0, 255);")
        self.instructions.setObjectName("instructions")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(740, 630, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.submit.setObjectName("submit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(24, 515, 441, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(260, 110, 401, 381))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.p1 = QtWidgets.QPushButton(self.page)
        self.p1.setGeometry(QtCore.QRect(12, -3, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.p1.setFont(font)
        self.p1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.p1.setObjectName("p1")
        self.p2 = QtWidgets.QPushButton(self.page)
        self.p2.setGeometry(QtCore.QRect(140, -3, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.p2.setFont(font)
        self.p2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 255);")
        self.p2.setObjectName("p2")
        self.p3 = QtWidgets.QPushButton(self.page)
        self.p3.setGeometry(QtCore.QRect(270, -3, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.p3.setFont(font)
        self.p3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.p3.setObjectName("p3")
        self.p4 = QtWidgets.QPushButton(self.page)
        self.p4.setGeometry(QtCore.QRect(12, 127, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.p4.setFont(font)
        self.p4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 255);")
        self.p4.setObjectName("p4")
        self.p5 = QtWidgets.QPushButton(self.page)
        self.p5.setGeometry(QtCore.QRect(140, 127, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.p5.setFont(font)
        self.p5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.p5.setObjectName("p5")
        self.p6 = QtWidgets.QPushButton(self.page)
        self.p6.setGeometry(QtCore.QRect(270, 127, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.p6.setFont(font)
        self.p6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 255);")
        self.p6.setObjectName("p6")
        self.p7 = QtWidgets.QPushButton(self.page)
        self.p7.setGeometry(QtCore.QRect(12, 258, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.p7.setFont(font)
        self.p7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.p7.setObjectName("p7")
        self.p8 = QtWidgets.QPushButton(self.page)
        self.p8.setGeometry(QtCore.QRect(140, 258, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.p8.setFont(font)
        self.p8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 85, 255);")
        self.p8.setObjectName("p8")
        self.p9 = QtWidgets.QPushButton(self.page)
        self.p9.setGeometry(QtCore.QRect(270, 258, 131, 131))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.p9.setFont(font)
        self.p9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 255, 255);")
        self.p9.setObjectName("p9")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(544, 515, 391, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 939, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.p1.clicked.connect(lambda:self.showl(self.p1))
        self.p2.clicked.connect(lambda: self.showl(self.p2))
        self.p3.clicked.connect(lambda: self.showl(self.p3))
        self.p4.clicked.connect(lambda: self.showl(self.p4))
        self.p5.clicked.connect(lambda: self.showl(self.p5))
        self.p6.clicked.connect(lambda: self.showl(self.p6))
        self.p7.clicked.connect(lambda: self.showl(self.p7))
        self.p8.clicked.connect(lambda: self.showl(self.p8))
        self.p9.clicked.connect(lambda: self.showl(self.p9))
        self.reset.clicked.connect(self.sreset)
        self.instructions.clicked.connect(self.showins)
        self.submit.clicked.connect(self.showplay)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def turn(self):
            if self.label.text().strip() == "1st Player Turn":
                    self.label.setText("2nd Player Turn")
                    self.label.setAlignment(QtCore.Qt.AlignCenter)
            else:
                    self.label.setText("1st Player Turn")
                    self.label.setAlignment(QtCore.Qt.AlignCenter)

    def sreset(self):
            self.p1.setText("*")
            self.p2.setText("*")
            self.p3.setText("*")
            self.p4.setText("*")
            self.p5.setText("*")
            self.p6.setText("*")
            self.p7.setText("*")
            self.p8.setText("*")
            self.p9.setText("*")
            self.p1.setEnabled(True)
            self.p2.setEnabled(True)
            self.p3.setEnabled(True)
            self.p4.setEnabled(True)
            self.p5.setEnabled(True)
            self.p6.setEnabled(True)
            self.p7.setEnabled(True)
            self.p8.setEnabled(True)
            self.p9.setEnabled(True)
            self.label.setText("                     1st Player Turn")
            self.a=True

    def showplay(self):
            self.play = QtWidgets.QMainWindow()
            self.ui = Ui_play()
            self.ui.setupUi(self.play)
            self.play.show()

    def showins(self):

            self.ins = QtWidgets.QMainWindow()
            self.ui = Ui_ins()
            self.ui.setupUi(self.ins)
            self.ins.show()

    def showl(self,p):

            if self.a:
                    p.setText("0")
                    self.a=False
            else:
                    p.setText("X")
                    self.a=True
            p.setEnabled(False)
            self.turn()
            self.check0()
            self.check1()
    def check0(self):
            if self.p1.text()== self.p2.text()== self.p3.text()=="0":
                    self.label.setText("Player 1 wins")
                    self.end()
            elif self.p4.text() == self.p5.text() == self.p6.text() == "0":
                    self.label.setText("Player 1 wins")
                    self.end()
            elif self.p7.text() == self.p8.text() == self.p9.text() == "0":
                    self.label.setText("Player 1 wins")
                    self.end()
            elif self.p1.text() == self.p5.text() == self.p9.text() == "0":
                    self.label.setText("Player 1 wins")
                    self.end()
            elif self.p3.text() == self.p5.text() == self.p7.text() == "0":
                    self.label.setText("Player 1 wins")
                    self.end()
            elif self.p1.text() == self.p4.text() == self.p7.text() == "0":
                    self.label.setText("Player 1 wins")
                    self.end()
            elif self.p2.text() == self.p5.text() == self.p8.text() == "0":
                    self.label.setText("Player 1 wins")
                    self.end()
            elif self.p3.text() == self.p6.text() == self.p9.text() == "0":
                    self.label.setText("Player 1 wins")
                    self.end()
            elif (len(self.p1.text()) >0) and (self.p2.text()=="X" or self.p2.text()=="0") and (self.p3.text()=="X" or self.p3.text()=="0") and (self.p4.text()=="X" or self.p4.text()=="0") and (self.p5.text()=="X" or self.p5.text()=="0") and (self.p6.text()=="X" or self.p6.text()=="0") and (self.p7.text()=="X" or self.p7.text()=="0") and (self.p8.text()=="X" or self.p8.text()=="0") and (self.p9.text()=="X" or self.p9.text()=="0"):
                    self.label.setText("Match ties")
                    self.end()

    def end(self):
            self.p1.setEnabled(False)
            self.p2.setEnabled(False)
            self.p3.setEnabled(False)
            self.p4.setEnabled(False)
            self.p5.setEnabled(False)
            self.p6.setEnabled(False)
            self.p7.setEnabled(False)
            self.p8.setEnabled(False)
            self.p9.setEnabled(False)
    def check1(self):
            if self.p1.text()== self.p2.text()== self.p3.text()=="X":
                    self.label.setText("Player 2 wins")
                    self.end()
            elif self.p4.text() == self.p5.text() == self.p6.text() == "X":
                    self.label.setText("Player 2 wins")
                    self.end()
            elif self.p7.text() == self.p8.text() == self.p9.text() == "X":
                    self.label.setText("Player 2 wins")
                    self.end()
            elif self.p1.text() == self.p5.text() == self.p9.text() == "X":
                    self.label.setText("Player 2 wins")
                    self.end()
            elif self.p3.text() == self.p5.text() == self.p7.text() == "X":
                    self.label.setText("Player 2 wins")
                    self.end()
            elif self.p1.text() == self.p4.text() == self.p7.text() == "X":
                    self.label.setText("Player 2 wins")
                    self.end()
            elif self.p2.text() == self.p5.text() == self.p8.text() == "X":
                    self.label.setText("Player 2 wins")
                    self.end()
            elif self.p3.text() == self.p6.text() == self.p9.text() == "X":
                    self.label.setText("Player 2 wins")
                    self.end()
            elif (self.p1.text == "X" or self.p1.text == "0") and (self.p2.text == "X" or self.p2.text == "0") and (
                    self.p3.text == "X" or self.p3.text == "0") and (self.p4.text == "X" or self.p4.text == "0") and (
                    self.p5.text == "X" or self.p5.text == "0") and (self.p6.text == "X" or self.p6.text == "0") and (
                    self.p7.text == "X" or self.p7.text == "0") and (self.p8.text == "X" or self.p8.text == "0") and (
                    self.p9.text == "X" or self.p9.text == "0"):
                    self.label.setText("Match ties")
                    self.end()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.labep1.setText(_translate("MainWindow", "                     DP TIC TAC TOE GAME"))
        self.reset.setText(_translate("MainWindow", "RESET"))
        self.instructions.setText(_translate("MainWindow", "INSTRUCTIONS"))
        self.submit.setText(_translate("MainWindow", "HOW TO PLAY"))
        self.label.setText(_translate("MainWindow", "                     1st Player Turn"))
        self.p1.setText(_translate("MainWindow", "*"))
        self.p2.setText(_translate("MainWindow", "*"))
        self.p3.setText(_translate("MainWindow", "*"))
        self.p4.setText(_translate("MainWindow", "*"))
        self.p5.setText(_translate("MainWindow", "*"))
        self.p6.setText(_translate("MainWindow", "*"))
        self.p7.setText(_translate("MainWindow", "*"))
        self.p8.setText(_translate("MainWindow", "*"))
        self.p9.setText(_translate("MainWindow", "*"))
        self.label_2.setText(_translate("MainWindow", "              2 Player Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
